"""added model terms_of_use

Revision ID: 088361d906e7
Revises: a92378014845
Create Date: 2026-02-26 13:30:18.378702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '088361d906e7'
down_revision: Union[str, None] = 'a92378014845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms_of_use',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('beat_id', sa.Integer(), nullable=False),
    sa.Column('recording_tracks', sa.Boolean(), nullable=False),
    sa.Column('commercial_perfomance', sa.Boolean(), nullable=False),
    sa.Column('rotation_on_the_radio', sa.Boolean(), nullable=False),
    sa.Column('music_video_recording', sa.Boolean(), nullable=False),
    sa.Column('release_of_copies', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['beat_id'], ['beats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terms_of_use_beat_id'), 'terms_of_use', ['beat_id'], unique=False)
    op.create_index(op.f('ix_terms_of_use_id'), 'terms_of_use', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_terms_of_use_id'), table_name='terms_of_use')
    op.drop_index(op.f('ix_terms_of_use_beat_id'), table_name='terms_of_use')
    op.drop_table('terms_of_use')
    # ### end Alembic commands ###
