"""add audio_key

Revision ID: 15f20ac2dd80
Revises: 1a92f108ece5
Create Date: 2026-03-03 15:03:06.922915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f20ac2dd80'
down_revision: Union[str, None] = '1a92f108ece5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beats', sa.Column('audio_key', sa.String(length=500), nullable=True))
    op.drop_column('beats', 'audio_file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beats', sa.Column('audio_file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('beats', 'audio_key')
    # ### end Alembic commands ###
