"""delete mp3 column, rename wav_path to audio_file_path

Revision ID: 1a92f108ece5
Revises: c2bcab96bf4d
Create Date: 2026-03-02 14:00:04.963383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a92f108ece5'
down_revision: Union[str, None] = 'c2bcab96bf4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
