"""added cover_path column to beats model

Revision ID: 5da3de0aa54c
Revises: 463a56df55f9
Create Date: 2026-02-28 16:31:35.057924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5da3de0aa54c'
down_revision: Union[str, None] = '463a56df55f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beats', sa.Column('cover_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beats', 'cover_path')
    # ### end Alembic commands ###
