"""add card_number

Revision ID: 98f029ccdc50
Revises: 674a49800c5d
Create Date: 2026-03-02 00:17:40.483942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f029ccdc50'
down_revision: Union[str, None] = '674a49800c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawals', sa.Column('card_number', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdrawals', 'card_number')
    # ### end Alembic commands ###
