"""initial

Revision ID: a92378014845
Revises: 
Create Date: 2026-02-16 16:03:13.268696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a92378014845'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('verification_type', sa.String(length=20), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verifications_email'), 'email_verifications', ['email'], unique=False)
    op.create_index(op.f('ix_email_verifications_expires_at'), 'email_verifications', ['expires_at'], unique=False)
    op.create_index(op.f('ix_email_verifications_is_used'), 'email_verifications', ['is_used'], unique=False)
    op.create_index(op.f('ix_email_verifications_token'), 'email_verifications', ['token'], unique=True)
    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('promo_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('max_uses_per_user', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('min_purchase_amount', sa.Float(), nullable=False),
    sa.Column('allowed_user_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_discount_amount', sa.Float(), nullable=False),
    sa.Column('total_purchases', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    op.create_index(op.f('ix_promo_codes_id'), 'promo_codes', ['id'], unique=False)
    op.create_index(op.f('ix_promo_codes_promo_type'), 'promo_codes', ['promo_type'], unique=False)
    op.create_index(op.f('ix_promo_codes_status'), 'promo_codes', ['status'], unique=False)
    op.create_index(op.f('ix_promo_codes_valid_from'), 'promo_codes', ['valid_from'], unique=False)
    op.create_index(op.f('ix_promo_codes_valid_until'), 'promo_codes', ['valid_until'], unique=False)
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('type', sa.Enum('LEASING', 'EXCLUSIVE', name='tarifftype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tariffs_id'), 'tariffs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('date_of_reg', sa.Date(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar_path', sa.String(length=500), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('prom_status', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('beats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('mp3_path', sa.String(length=500), nullable=True),
    sa.Column('wav_path', sa.String(length=500), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('tempo', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=10), nullable=False),
    sa.Column('audio_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('audio_fingerprint_timings', sa.String(length=2000), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('promotion_status', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('MODERATED', 'AVAILABLE', 'DENIED', 'SOLD', name='statustype'), nullable=False),
    sa.Column('rejection_reason', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beats_audio_fingerprint'), 'beats', ['audio_fingerprint'], unique=False)
    op.create_index(op.f('ix_beats_author_id'), 'beats', ['author_id'], unique=False)
    op.create_index(op.f('ix_beats_created_at'), 'beats', ['created_at'], unique=False)
    op.create_index(op.f('ix_beats_genre'), 'beats', ['genre'], unique=False)
    op.create_index(op.f('ix_beats_promotion_status'), 'beats', ['promotion_status'], unique=False)
    op.create_index(op.f('ix_beats_status'), 'beats', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('tpay_payment_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'EXPIRED', name='paymentstatus'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_tpay_payment_id'), 'payments', ['tpay_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('problem_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_created_at'), 'requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_requests_id'), 'requests', ['id'], unique=False)
    op.create_index(op.f('ix_requests_problem_type'), 'requests', ['problem_type'], unique=False)
    op.create_index(op.f('ix_requests_status'), 'requests', ['status'], unique=False)
    op.create_index(op.f('ix_requests_user_id'), 'requests', ['user_id'], unique=False)
    op.create_table('user_balance_operations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'PURCHASE', 'REFUND', 'BONUS', name='balanceoperationtype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_balance_operations_created_at'), 'user_balance_operations', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_balance_operations_user_id'), 'user_balance_operations', ['user_id'], unique=False)
    op.create_table('user_promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('promo_code_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_promo_codes_activated_at'), 'user_promo_codes', ['activated_at'], unique=False)
    op.create_index(op.f('ix_user_promo_codes_expires_at'), 'user_promo_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_promo_codes_id'), 'user_promo_codes', ['id'], unique=False)
    op.create_index(op.f('ix_user_promo_codes_promo_code_id'), 'user_promo_codes', ['promo_code_id'], unique=False)
    op.create_index(op.f('ix_user_promo_codes_status'), 'user_promo_codes', ['status'], unique=False)
    op.create_index(op.f('ix_user_promo_codes_user_id'), 'user_promo_codes', ['user_id'], unique=False)
    op.create_table('beat_pricing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('beat_id', sa.Integer(), nullable=False),
    sa.Column('tariff_name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['beat_id'], ['beats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tariff_name'], ['tariffs.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beat_id', 'tariff_name', name='_bit_tariff_uc')
    )
    op.create_index(op.f('ix_beat_pricing_beat_id'), 'beat_pricing', ['beat_id'], unique=False)
    op.create_index(op.f('ix_beat_pricing_created_at'), 'beat_pricing', ['created_at'], unique=False)
    op.create_index(op.f('ix_beat_pricing_id'), 'beat_pricing', ['id'], unique=False)
    op.create_index(op.f('ix_beat_pricing_is_available'), 'beat_pricing', ['is_available'], unique=False)
    op.create_index(op.f('ix_beat_pricing_tariff_name'), 'beat_pricing', ['tariff_name'], unique=False)
    op.create_table('beat_promotions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('beat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['beat_id'], ['beats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_beats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('beat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beat_id'], ['beats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_beats_beat_id'), 'favorite_beats', ['beat_id'], unique=False)
    op.create_index(op.f('ix_favorite_beats_user_id'), 'favorite_beats', ['user_id'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchaser_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('beat_id', sa.Integer(), nullable=False),
    sa.Column('tariff_name', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['beat_id'], ['beats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchaser_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tariff_name'], ['tariffs.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_beat_id'), 'purchases', ['beat_id'], unique=False)
    op.create_index(op.f('ix_purchases_purchaser_id'), 'purchases', ['purchaser_id'], unique=False)
    op.create_index(op.f('ix_purchases_seller_id'), 'purchases', ['seller_id'], unique=False)
    op.create_index(op.f('ix_purchases_tariff_name'), 'purchases', ['tariff_name'], unique=False)
    op.create_table('download_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('beat_id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('max_downloads', sa.Integer(), nullable=False),
    sa.Column('downloads_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_download_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beat_id'], ['beats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_tokens_token'), 'download_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_download_tokens_token'), table_name='download_tokens')
    op.drop_table('download_tokens')
    op.drop_index(op.f('ix_purchases_tariff_name'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_seller_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_purchaser_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_beat_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_favorite_beats_user_id'), table_name='favorite_beats')
    op.drop_index(op.f('ix_favorite_beats_beat_id'), table_name='favorite_beats')
    op.drop_table('favorite_beats')
    op.drop_table('beat_promotions')
    op.drop_index(op.f('ix_beat_pricing_tariff_name'), table_name='beat_pricing')
    op.drop_index(op.f('ix_beat_pricing_is_available'), table_name='beat_pricing')
    op.drop_index(op.f('ix_beat_pricing_id'), table_name='beat_pricing')
    op.drop_index(op.f('ix_beat_pricing_created_at'), table_name='beat_pricing')
    op.drop_index(op.f('ix_beat_pricing_beat_id'), table_name='beat_pricing')
    op.drop_table('beat_pricing')
    op.drop_index(op.f('ix_user_promo_codes_user_id'), table_name='user_promo_codes')
    op.drop_index(op.f('ix_user_promo_codes_status'), table_name='user_promo_codes')
    op.drop_index(op.f('ix_user_promo_codes_promo_code_id'), table_name='user_promo_codes')
    op.drop_index(op.f('ix_user_promo_codes_id'), table_name='user_promo_codes')
    op.drop_index(op.f('ix_user_promo_codes_expires_at'), table_name='user_promo_codes')
    op.drop_index(op.f('ix_user_promo_codes_activated_at'), table_name='user_promo_codes')
    op.drop_table('user_promo_codes')
    op.drop_index(op.f('ix_user_balance_operations_user_id'), table_name='user_balance_operations')
    op.drop_index(op.f('ix_user_balance_operations_created_at'), table_name='user_balance_operations')
    op.drop_table('user_balance_operations')
    op.drop_index(op.f('ix_requests_user_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_status'), table_name='requests')
    op.drop_index(op.f('ix_requests_problem_type'), table_name='requests')
    op.drop_index(op.f('ix_requests_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_created_at'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_tpay_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_beats_status'), table_name='beats')
    op.drop_index(op.f('ix_beats_promotion_status'), table_name='beats')
    op.drop_index(op.f('ix_beats_genre'), table_name='beats')
    op.drop_index(op.f('ix_beats_created_at'), table_name='beats')
    op.drop_index(op.f('ix_beats_author_id'), table_name='beats')
    op.drop_index(op.f('ix_beats_audio_fingerprint'), table_name='beats')
    op.drop_table('beats')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tariffs_id'), table_name='tariffs')
    op.drop_table('tariffs')
    op.drop_index(op.f('ix_promo_codes_valid_until'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_valid_from'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_status'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_promo_type'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_id'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_index(op.f('ix_email_verifications_token'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_is_used'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_expires_at'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_email'), table_name='email_verifications')
    op.drop_table('email_verifications')
    # ### end Alembic commands ###
