"""add email_change

Revision ID: ab1ae9aa454a
Revises: 5bfc618a71ef
Create Date: 2026-03-05 18:07:19.446966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1ae9aa454a'
down_revision: Union[str, None] = '5bfc618a71ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verifications', sa.Column('new_email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_email_verifications_new_email'), 'email_verifications', ['new_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_verifications_new_email'), table_name='email_verifications')
    op.drop_column('email_verifications', 'new_email')
    # ### end Alembic commands ###
