"""add aggrement fields

Revision ID: b1b944475f17
Revises: d2e02745de1c
Create Date: 2026-03-16 00:38:26.697879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1b944475f17'
down_revision: Union[str, None] = 'd2e02745de1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('agreed_to_offer', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('agreed_to_privacy_policy', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('agreed_to_terms', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'agreed_to_terms')
    op.drop_column('users', 'agreed_to_privacy_policy')
    op.drop_column('users', 'agreed_to_offer')
    # ### end Alembic commands ###
