"""delete mp3 column, rename wav_path to audio_file_path

Revision ID: c2bcab96bf4d
Revises: 98f029ccdc50
Create Date: 2026-03-02 13:59:52.573770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2bcab96bf4d'
down_revision: Union[str, None] = '98f029ccdc50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beats', sa.Column('audio_file_path', sa.String(length=500), nullable=True))
    op.drop_column('beats', 'mp3_path')
    op.drop_column('beats', 'wav_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beats', sa.Column('wav_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('beats', sa.Column('mp3_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('beats', 'audio_file_path')
    # ### end Alembic commands ###
