"""add_subscription_fields

Revision ID: dd7e76d6144b
Revises: 15f20ac2dd80
Create Date: 2026-03-04 19:16:21.327322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd7e76d6144b'
down_revision: Union[str, None] = '15f20ac2dd80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_start', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('subscription_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_end')
    op.drop_column('users', 'subscription_start')
    # ### end Alembic commands ###
